version: '3'
services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.1.2
    container_name: xxl-job-admin
    restart: always
    environment:
      - PARAMS=--spring.datasource.url=jdbc:mysql://10.888.8.888:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.password=password
    volumes:
      - /mnt/xxl-job:/data/applogs
    ports:
      - "18080:8080"