version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=database_name
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - /mnt/db_data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"